#!C:\Users\SSAFY\Desktop\Data\S11P21D207\DT\FastAPI\todo\irr\irr_env\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
